---
- name: Deploy Maven Artifact
  hosts: local
  become: yes
  tasks:
    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/hellomaven_CIA/target/MyMavenApp505-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/MyMavenApp505.jar"
