---
- name: Deploy Maven Artifact
  hosts: local
  become: yes
  tasks:
    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/mvaven505A-CI/target/mvaven505A-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/mvaven505A.jar"

